const SERVICES = [{"id": "computer-repair", "name": "Computer Repair", "description": "Hardware diagnostics, upgrades, repairs and troubleshooting.", "min": 350, "max": 10000, "icon": "🛠️"}, {"id": "smartphone-repair", "name": "Smartphone Repair", "description": "Screen, battery, charging and software support.", "min": 100, "max": 500, "icon": "📱"}, {"id": "printer-solutions", "name": "Office Printer Solutions", "description": "Printer setup, troubleshooting, maintenance and configuration.", "min": 100, "max": 1000, "icon": "🖨️"}, {"id": "automation", "name": "Home or Office Automation", "description": "Smart devices, networking and practical automation solutions.", "min": 500, "max": 2000, "icon": "🏠"}, {"id": "device-solutions", "name": "Any Device Solutions", "description": "Technical support for computers, phones, tablets and other devices.", "min": 100, "max": 10000, "icon": "💻"}, {"id": "cctv", "name": "CCTV Solutions & Installations", "description": "CCTV planning, supply, installation and configuration.", "min": 100, "max": 10000, "icon": "📹"}, {"id": "dstv", "name": "DStv Solutions", "description": "DStv setup, signal troubleshooting and installation support.", "min": 100, "max": 1200, "icon": "📡"}, {"id": "programming", "name": "Programming", "description": "Custom websites, software and programming assistance.", "min": 100, "max": 2000, "icon": "💻"}];
const WHATSAPP="27848775087";
let cart=JSON.parse(localStorage.getItem("itsp_cart")||"[]");
const $=id=>document.getElementById(id);
const money=n=>"R"+Number(n).toLocaleString("en-ZA",{maximumFractionDigits:0});
function saveCart(){localStorage.setItem("itsp_cart",JSON.stringify(cart));renderCart();}
function renderServices(){$("serviceGrid").innerHTML=SERVICES.map(s=>`<article class="service-card"><div class="service-icon">${s.icon}</div><h3>${s.name}</h3><p>${s.description}</p><div class="price-row"><small>Estimated range</small><strong>${money(s.min)}–${money(s.max)}</strong></div><button class="add-btn" onclick="addToCart('${s.id}')">Add to cart</button></article>`).join("");}
function addToCart(id){const s=SERVICES.find(x=>x.id===id),e=cart.find(x=>x.id===id);if(e)e.qty++;else cart.push({id:s.id,name:s.name,price:s.min,qty:1});saveCart();openCart();}
function removeFromCart(id){cart=cart.filter(x=>x.id!==id);saveCart();}
function changeQty(id,d){const x=cart.find(y=>y.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)removeFromCart(id);else saveCart();}
function total(){return cart.reduce((sum,x)=>sum+x.price*x.qty,0);}
function renderCart(){$("cartCount").textContent=cart.reduce((n,x)=>n+x.qty,0);$("cartTotal").textContent=money(total());$("checkoutTotal").textContent=money(total());$("cartItems").innerHTML=cart.length?cart.map(x=>`<div class="cart-line"><div class="cart-line-top"><b>${x.name}</b><strong>${money(x.price*x.qty)}</strong></div><p>Starting/estimated amount: ${money(x.price)} each</p><div class="qty"><button onclick="changeQty('${x.id}',-1)">−</button><b>${x.qty}</b><button onclick="changeQty('${x.id}',1)">+</button><button class="remove" onclick="removeFromCart('${x.id}')">Remove</button></div></div>`).join(""):'<div class="empty">Your cart is empty.<br>Add a service to begin.</div>';}
function openCart(){$("cartDrawer").classList.add("open");$("overlay").classList.add("open");}
function closeCart(){$("cartDrawer").classList.remove("open");$("overlay").classList.remove("open");}
function openCheckout(){if(!cart.length){alert("Please add at least one service to your cart.");return}closeCart();$("checkoutModal").classList.add("open");}
function closeCheckout(){$("checkoutModal").classList.remove("open");}
function orderNumber(){const d=new Date();return "ITSP-"+d.getFullYear()+String(d.getMonth()+1).padStart(2,"0")+String(d.getDate()).padStart(2,"0")+"-"+Math.floor(1000+Math.random()*9000);}
$("checkoutForm").addEventListener("submit",e=>{e.preventDefault();const order=orderNumber(),name=$("customerName").value.trim(),phone=$("customerPhone").value.trim(),email=$("customerEmail").value.trim(),address=$("customerAddress").value.trim(),notes=$("customerNotes").value.trim(),payment=document.querySelector('input[name="payment"]:checked').value;const lines=cart.map(x=>`• ${x.name} x${x.qty} — ${money(x.price*x.qty)}`).join("\n");const message=`New IT Specialist Pro Order ${order}\n\nCustomer: ${name}\nPhone: ${phone}${email?"\nEmail: "+email:""}\nAddress: ${address}\nPayment: ${payment.toUpperCase()}\n\nServices:\n${lines}\n\nEstimated Total: ${money(total())}${notes?"\n\nNotes: "+notes:""}`;window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(message)}`,"_blank");localStorage.removeItem("itsp_cart");cart=[];renderCart();closeCheckout();alert(`Order ${order} prepared. WhatsApp will open with your order details. Please follow the payment instructions sent by IT Specialist Pro.`);});
document.querySelectorAll('input[name="payment"]').forEach(r=>r.addEventListener("change",e=>{$("bankBox").style.display=e.target.value==="eft"?"block":"none";}));
$("openCartBtn").onclick=openCart;$("closeCartBtn").onclick=closeCart;$("overlay").onclick=closeCart;$("checkoutBtn").onclick=openCheckout;$("closeCheckoutBtn").onclick=closeCheckout;$("checkoutModal").addEventListener("click",e=>{if(e.target===$("checkoutModal"))closeCheckout();});$("year").textContent=new Date().getFullYear();renderServices();renderCart();
